<a href="https://colab.research.google.com/github/fragenabhishek/ML/blob/main/ML16_NeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
dataset=pd.read_csv("Churn_Modelling.csv")

In [ ]:
X=dataset.iloc[:,3:13].values
Y=dataset.iloc[:,13].values

In [ ]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
Y

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categories='auto', drop=None, sparse=True, handle_unknown='error')
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.20,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
X_train.shape

(8000, 16934)

In [ ]:
import keras

Using TensorFlow backend.


In [ ]:
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras import Sequential

In [ ]:
classifier=Sequential()

In [ ]:
classifier.add(Dense(6,activation="relu",kernel_initializer="uniform"))

In [ ]:
classifier.add(Dense(6,activation="relu",kernel_initializer="uniform"))

In [ ]:

classifier.add(Dense(1,activation="sigmoid",kernel_initializer="uniform"))

In [ ]:
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["Accuracy"])

In [ ]:
classifier.fit(X_train,Y_train,batch_size=10,epochs=100)

Epoch 1/100
800/800 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.0000e+00
Epoch 2/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4571 - accuracy: 0.0000e+00
Epoch 3/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3967 - accuracy: 0.0000e+00
Epoch 4/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3212 - accuracy: 0.0000e+00
Epoch 5/100
800/800 [==============================] - 2s 2ms/step - loss: 0.2785 - accuracy: 0.0000e+00
Epoch 6/100
800/800 [==============================] - 2s 2ms/step - loss: 0.2668 - accuracy: 0.0000e+00
Epoch 7/100
800/800 [==============================] - 2s 2ms/step - loss: 0.2632 - accuracy: 0.0000e+00
Epoch 8/100
800/800 [==============================] - 2s 2ms/step - loss: 0.2609 - accuracy: 0.0000e+00
Epoch 9/100
800/800 [==============================] - 2s 2ms/step - loss: 0.2583 - accuracy: 0.0000e+00
Epoch 10/100
800/800 [==============================] -

In [ ]:
Y_pred=classifier.predict(X_test)

In [ ]:
Y_pred
Y_pred=(Y_pred>0.5)


In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_pred)

In [ ]:
cm

array([[1595,    0],
       [ 405,    0]])